[tool.poetry]
name = "langchain-demo"
version = "0.1.0"
description = ""
authors = ["Shioya"]

[tool.poetry.dependencies]
python = "^3.11.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
